name: Bug report
description: 报告一个问题或缺陷
title: "[Bug] 描述问题"
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: 描述
      description: 清晰描述问题现象
      placeholder: 发生了什么、期望是什么
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 复现步骤
      description: 提供最小可复现步骤
      placeholder: 1. ... 2. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 期望行为
    validations:
      required: false
  - type: input
    id: env
    attributes:
      label: 环境信息
      placeholder: OS/版本/依赖等
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: 其他信息
    validations:
      required: false
