name: Feature request
description: 提出一个功能建议
title: "[Feature] 描述需求"
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: 背景/问题
      description: 当前痛点或场景
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: 方案构想
      description: 期望的功能与实现思路
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: 其他信息
    validations:
      required: false
